CREATE TABLE user_profiles (
  id BIGINT IDENTITY NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(255) NOT NULL,
  role VARCHAR(255) NOT NULL
);

CREATE TABLE transactions (
  id BIGINT IDENTITY NOT NULL PRIMARY KEY,
  date TIMESTAMP NOT NULL,
  action varchar(255) NOT NULL,
  amount INT NOT NULL,
  source VARCHAR(255) NOT NULL
);
